projects:
  smokefree-initiative-service:
    schemaPath: >-
      ../../local-motion/smokefree-initiative-service/src/main/resources/public/schema.graphql
    extensions:
      endpoints:
        dev:
          url: 'http://localhost:8086/api/graphql'
          headers:
            Authorization2: "Bearer ${env:ID_TOKEN}"
